apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-v1-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website-v1
    spec:
      containers:
      - name: website-demo
        image: <image_name>
        ports:
        - name: website-port
          containerPort: 80
